/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * @fastify/swagger
 * OpenAPI spec version: 9.4.2
 */

/**
 * Successful response
 */
export type GetItems201 = {
  id?: number;
  name?: string;
};
